# Generated by Django 4.0.4 on 2022-04-20 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job1', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.balance')),
                ('income', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.income')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.user')),
            ],
        ),
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.user'),
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_house', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.user')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takeout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concert', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shopping', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.user')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('groceries', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_mortgage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('electrical', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mobile', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transportation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car', models.DecimalField(decimal_places=2, max_digits=10)),
                ('groceries', models.DecimalField(decimal_places=2, max_digits=10)),
                ('education', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.user')),
            ],
        ),
        migrations.AddField(
            model_name='balance',
            name='expenses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.expenses'),
        ),
        migrations.AddField(
            model_name='balance',
            name='income',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.income'),
        ),
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.user'),
        ),
    ]
