# Generated by Django 4.0.4 on 2022-04-23 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('transc_name', models.CharField(max_length=30)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='balance',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='cable',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='car',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='education',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='electrical',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='gas',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='groceries',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='rent_mortgage',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='transportation',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='groceries',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='transportation',
        ),
        migrations.RemoveField(
            model_name='goals',
            name='buy_house',
        ),
        migrations.RemoveField(
            model_name='goals',
            name='travel',
        ),
        migrations.RemoveField(
            model_name='income',
            name='job1',
        ),
        migrations.RemoveField(
            model_name='savings',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='savings',
            name='deposit',
        ),
        migrations.AddField(
            model_name='balance',
            name='difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bills',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bills',
            name='isPaid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.CharField(default='Caterogy', max_length=30),
        ),
        migrations.AddField(
            model_name='goals',
            name='amount_saved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='goals',
            name='amount_to_save',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='goals',
            name='category',
            field=models.CharField(default='category', max_length=30),
        ),
        migrations.AddField(
            model_name='goals',
            name='goal_name',
            field=models.CharField(default='goal_name', max_length=30),
        ),
        migrations.AddField(
            model_name='income',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='income',
            name='income_name',
            field=models.CharField(max_length=30, default='income_name'),
        ),
        migrations.AddField(
            model_name='income',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='income',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AddField(
            model_name='savings',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='balance',
            name='income',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.income'),
        ),
        migrations.AlterField(
            model_name='savings',
            name='income',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.income'),
        ),
        migrations.AlterField(
            model_name='savings',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Expenses',
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.user'),
        ),
        migrations.AddField(
            model_name='balance',
            name='transaction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.transaction'),
        ),
        migrations.AddField(
            model_name='bills',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.transaction'),
        ),
        migrations.AddField(
            model_name='budget',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.transaction'),
        ),
        migrations.AddField(
            model_name='savings',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.transaction'),
        ),
    ]
