# Generated by Django 4.0.4 on 2022-04-25 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goals',
            name='category',
        ),
    ]
