# Generated by Django 4.0.4 on 2022-04-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_transaction_remove_balance_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income_name',
            field=models.CharField(default='income_name', max_length=20),
        ),
    ]
